/*==================== Generator information =============================
* This code was generated by php-ext-gen (v {{ software.version }})
* Generation Date: {{ date()|date("Y/m/d") }}
* Target engine: {{ engine.name }} (v {{ engine.version }})
* Generator: {{ generator.name }}
========================================================================*/
