# Metadata schema

#---------
# Global data

name:           //str
version;        // str

[autoconf]:     // <TODO>

[extra_files]:
  <filename>:
    [expand]:		// bool - Run through twig ? Default=false
  ...
	
[functions]:
  - <function-name>
  ...

[constants]:    // array of constant definitions

#---------
# Definition of a constant

<constant-name>: // arr
  type:         //str - one of (null,bool,int,double,string,array)
  [computed]:   // bool|string - only if type!=null. Defaults to false
                // Possible values: true, false, use-name
                // use-name -> Use constant name as computed value (in this case,
                // value param is ignored)
  value:        // str - if computed==true, value is formula.

#---------
# Definition of a function

return_type:    // str - one of (null,bool,int,double,string,array)
arguments:      // array of call argument definitions

#---------
# Definition of a call argument

<arg-name>:     // arr
  type:         // str - one of (bool,int,double,string,array) or mixed/[a_scalar_type]
  [ref]:        // bool - pass by ref ? Default: false
  [nullok]:     // bool - Default: false
  [default]:    // str - must be null if type is array or mixed.
                //       If not set (default case), the argument is required
