#
#==============================================================================

SUBDIRS = newt dummy1 scream

include ../make.vars
include ../make.common

#-----------------------------

.PHONY: all examples clean

all:

clean: clean_base

#-----------------------------------------------------------------------------
