php_info_print_table_start();

php_info_print_table_row(2, "This extension was generated by","php-ext-gen");
php_info_print_table_row(2, "Generator version","{{ software.version }}");
php_info_print_table_row(2, "Generation Date","{{ date()|date("Y/m/d") }}");
php_info_print_table_row(2, "Target PHP engine","{{ engine.name }}");
php_info_print_table_row(2, "Target version","{{ engine.version }}");

php_info_print_table_end();
