php_info_print_table_start();

php_info_print_table_row(2, "Extension version", PHP_{{ uname }}_VERSION);
php_info_print_table_row(2, "Generated by", "php-ext-gen");
php_info_print_table_row(2, "Generator version", EXTGEN_VERSION);
php_info_print_table_row(2, "Generation Date", EXTGEN_GENERATION_DATE);
php_info_print_table_row(2, "Target PHP engine", EXTGEN_TARGET_ENGINE);
php_info_print_table_row(2, "Target version", EXTGEN_TARGET_VERSION);

php_info_print_table_end();
